const sequelize = require('../config/database');
const { DataTypes } = require('sequelize');

const CrossWord = sequelize.define('CrossWord', {
    level: {
        type: DataTypes.INTEGER,
    },
    A1: {type: DataTypes.INTEGER},
    A2: {type: DataTypes.INTEGER},
    A3: {type: DataTypes.INTEGER},
    A4: {type: DataTypes.INTEGER},
    A5: {type: DataTypes.INTEGER},
    A6: {type: DataTypes.INTEGER},
    A7: {type: DataTypes.INTEGER},
    A8: {type: DataTypes.INTEGER},
    A9: {type: DataTypes.INTEGER},
    A10: {type: DataTypes.INTEGER},
    B1: {type: DataTypes.INTEGER},
    B2: {type: DataTypes.INTEGER},
    B3: {type: DataTypes.INTEGER},
    B4: {type: DataTypes.INTEGER},
    B5: {type: DataTypes.INTEGER},
    B6: {type: DataTypes.INTEGER},
    B7: {type: DataTypes.INTEGER},
    B8: {type: DataTypes.INTEGER},
    B9: {type: DataTypes.INTEGER},
    B10: {type: DataTypes.INTEGER},
    C1: {type: DataTypes.INTEGER},
    C2: {type: DataTypes.INTEGER},
    C3: {type: DataTypes.INTEGER},
    C4: {type: DataTypes.INTEGER},
    C5: {type: DataTypes.INTEGER},
    C6: {type: DataTypes.INTEGER},
    C7: {type: DataTypes.INTEGER},
    C8: {type: DataTypes.INTEGER},
    C9: {type: DataTypes.INTEGER},
    C10: {type: DataTypes.INTEGER},
    D1: {type: DataTypes.INTEGER},
    D2: {type: DataTypes.INTEGER},
    D3: {type: DataTypes.INTEGER},
    D4: {type: DataTypes.INTEGER},
    D5: {type: DataTypes.INTEGER},
    D6: {type: DataTypes.INTEGER},
    D7: {type: DataTypes.INTEGER},
    D8: {type: DataTypes.INTEGER},
    D9: {type: DataTypes.INTEGER},
    D10: {type: DataTypes.INTEGER},
    E1: {type: DataTypes.INTEGER},
    E2: {type: DataTypes.INTEGER},
    E3: {type: DataTypes.INTEGER},
    E4: {type: DataTypes.INTEGER},
    E5: {type: DataTypes.INTEGER},
    E6: {type: DataTypes.INTEGER},
    E7: {type: DataTypes.INTEGER},
    E8: {type: DataTypes.INTEGER},
    E9: {type: DataTypes.INTEGER},
    E10: {type: DataTypes.INTEGER},
    F1: {type: DataTypes.INTEGER},
    F2: {type: DataTypes.INTEGER},
    F3: {type: DataTypes.INTEGER},
    F4: {type: DataTypes.INTEGER},
    F5: {type: DataTypes.INTEGER},
    F6: {type: DataTypes.INTEGER},
    F7: {type: DataTypes.INTEGER},
    F8: {type: DataTypes.INTEGER},
    F9: {type: DataTypes.INTEGER},
    F10: {type: DataTypes.INTEGER},
    G1: {type: DataTypes.INTEGER},
    G2: {type: DataTypes.INTEGER},
    G3: {type: DataTypes.INTEGER},
    G4: {type: DataTypes.INTEGER},
    G5: {type: DataTypes.INTEGER},
    G6: {type: DataTypes.INTEGER},
    G7: {type: DataTypes.INTEGER},
    G8: {type: DataTypes.INTEGER},
    G9: {type: DataTypes.INTEGER},
    G10: {type: DataTypes.INTEGER},
    H1: {type: DataTypes.INTEGER},
    H2: {type: DataTypes.INTEGER},
    H3: {type: DataTypes.INTEGER},
    H4: {type: DataTypes.INTEGER},
    H5: {type: DataTypes.INTEGER},
    H6: {type: DataTypes.INTEGER},
    H7: {type: DataTypes.INTEGER},
    H8: {type: DataTypes.INTEGER},
    H9: {type: DataTypes.INTEGER},
    H10: {type: DataTypes.INTEGER},
    I1: {type: DataTypes.INTEGER},
    I2: {type: DataTypes.INTEGER},
    I3: {type: DataTypes.INTEGER},
    I4: {type: DataTypes.INTEGER},
    I5: {type: DataTypes.INTEGER},
    I6: {type: DataTypes.INTEGER},
    I7: {type: DataTypes.INTEGER},
    I8: {type: DataTypes.INTEGER},
    I9: {type: DataTypes.INTEGER},
    I10: {type: DataTypes.INTEGER},
    J1: {type: DataTypes.INTEGER},
    J2: {type: DataTypes.INTEGER},
    J3: {type: DataTypes.INTEGER},
    J4: {type: DataTypes.INTEGER},
    J5: {type: DataTypes.INTEGER},
    J6: {type: DataTypes.INTEGER},
    J7: {type: DataTypes.INTEGER},
    J8: {type: DataTypes.INTEGER},
    J9: {type: DataTypes.INTEGER},
    J10: {type: DataTypes.INTEGER},
})

// Grid.associate = (models) => {
//     Grid.belongsToMany(models.User, {
//       through: models.UsersGrids,
//       foreignKey: 'gridId',
//     });
//     Grid.hasMany(models.UsersGridsLines, { 
//         foreignKey: 'gridId', 
//         as: 'grids' 
//     });
// };


module.exports = CrossWord;